### ISSUE TITLE
Sentinel crashes mogwaid

### ISSUE THREAD

**Issue by mooleshacat** [mogwaicoin/mogwai-sentinel#4]
Sentinel crashes mogwaid:

> mogwai2@easyxpool:~/mogwai-sentinel$ cd ~/mogwai-sentinel/ && SENTINEL_DEBUG=1 ./venv/bin/python bin/sentinel.py
> 2018-10-22 20:32:16 [info]: SCHEMA_VERSION (code) = [20170111-1]
> 2018-10-22 20:32:16 [info]: DB_SCHEMA_VERSION = [20170111-1]
> ('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_NEXT_SENTINEL_CHECK_AT'])
> 2018-10-22 20:32:16 current_time = 1540240336
> 2018-10-22 20:32:16 next_run_time = 0
> 2018-10-22 20:32:16 Delay of [16] seconds for cron minute offset
> 
> 
> ('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_NEXT_SENTINEL_CHECK_AT'])
> ('SELECT "t1"."id", "t1"."parent_id", "t1"."object_creation_time", "t1"."object_hash", "t1"."object_parent_hash", "t1"."object_type", "t1"."object_revision", "t1"."object_fee_tx", "t1"."yes_count", "t1"."no_count", "t1"."abstain_count", "t1"."absolute_yes_count" FROM "governance_objects" AS t1', [])
> 2018-10-22 20:32:32 in sentinel_ping
> 2018-10-22 20:32:32 leaving sentinel_ping
> ('SELECT "t1"."id", "t1"."governance_object_id", "t1"."name", "t1"."url", "t1"."start_epoch", "t1"."end_epoch", "t1"."payment_address", "t1"."payment_amount", "t1"."object_hash" FROM "proposals" AS t1', [])
> ('SELECT Count(*) FROM "superblocks" AS t1 INNER JOIN "governance_objects" AS t2 ON ("t1"."governance_object_id" = "t2"."id") INNER JOIN "votes" AS t3 ON ("t2"."id" = "t3"."governance_object_id") INNER JOIN "signals" AS t4 ON ("t3"."signal_id" = "t4"."id") INNER JOIN "outcomes" AS t5 ON ("t3"."outcome_id" = "t5"."id") WHERE ((("t1"."event_block_height" = ?) AND ("t3"."signal_id" = ?)) AND ("t3"."outcome_id" = ?))', [80640, 1, 1])
> Traceback (most recent call last):
>   File "bin/sentinel.py", line 265, in <module>
>     main()
>   File "bin/sentinel.py", line 221, in main
>     attempt_superblock_creation(mogwaid)
>   File "bin/sentinel.py", line 109, in attempt_superblock_creation
>     proposals = Proposal.approved_and_ranked(proposal_quorum=mogwaid.governance_quorum(), next_superblock_max_budget=mogwaid.next_superblock_max_budget())
>   File "lib/mogwaid.py", line 136, in next_superblock_max_budget
>     next_allocation = self.get_superblock_budget_allocation(next_superblock_height)
>   File "lib/mogwaid.py", line 126, in get_superblock_budget_allocation
>     return Decimal(self.rpc_command('getsuperblockbudget', height))
>   File "lib/mogwaid.py", line 42, in rpc_command
>     return self.rpc_connection.__getattr__(params[0])(*params[1:])
>   File "/home/mogwai2/mogwai-sentinel/venv/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 139, in __call__
>     response = self._get_response()
>   File "/home/mogwai2/mogwai-sentinel/venv/local/lib/python2.7/site-packages/bitcoinrpc/authproxy.py", line 179, in _get_response
>     http_response = self.__conn.getresponse()
>   File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 438, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 402, in _read_status
>     raise BadStatusLine(line)
> httplib.BadStatusLine: ''
> ('SELECT "t1"."id", "t1"."name", "t1"."value", "t1"."created_at", "t1"."updated_at" FROM "settings" AS t1 WHERE ("t1"."name" = ?) LIMIT 1 OFFSET 0', [u'__transient_SENTINEL_RUNNING'])
> ('DELETE FROM "settings" WHERE ("id" = ?)', [2])
> mogwai2@easyxpool:~/mogwai-sentinel$

This is a reinstall with a reindex...

I used same collateral, should I send it again and start over with the collateral?

Thanks

**Comment by darkfriend77** [comment]
sry, I forgot to fix it here while I posted already the fix on discord.

It's now fixed.

https://github.com/mogwaicoin/mogwai-sentinel/commit/ce38cce3f55915beda1937261eba048317c2cf97

**Comment by mooleshacat** [comment]
Thanks, I will pull it now and see if it works :)

I thought it was something I did wrong.

**Comment by mooleshacat** [comment]
Confirmed working with latest fix.

Thanks :)
